In [333]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [334]:
df = pd.read_csv("ratings_small.csv")
meta=pd.read_csv("movies_metadata.csv")
df.drop(['timestamp'],axis=1,inplace= True)
df.head()

userId  movieId  rating
0       1       31     2.5
1       1     1029     3.0
2       1     1061     3.0
3       1     1129     2.0
4       1     1172     4.0

In [335]:
pivoted = df.pivot(index="userId", columns="movieId", values="rating")
pivoted

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN     4.0     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     NaN     NaN     4.0     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         5.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  161084  161155  161594  161830  161918  161944  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
668         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  162376  162542  162672  163949  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN  

[671 rows x 9066 columns]

In [336]:
df[df['userId']==662][0:10]

userId  movieId  rating
98656     662        2     5.0
98657     662       10     3.0
98658     662       19     2.0
98659     662       34     4.0
98660     662       39     3.0
98661     662       47     3.0
98662     662      150     4.0
98663     662      158     4.0
98664     662      165     3.0
98665     662      185     4.0

## ` Normalising the data to be around 0 `

In [337]:
avrg=pivoted.mean(axis=1)
centerd_pivoted=pivoted.sub(avrg,axis=0)
centerd_pivoted

movieId    1       2       3       4       5         6       7       8       \
userId                                                                        
1             NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
2             NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
3             NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
4             NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
5             NaN     NaN    0.09     NaN     NaN       NaN     NaN     NaN   
...           ...     ...     ...     ...     ...       ...     ...     ...   
667           NaN     NaN     NaN     NaN     NaN  0.352941     NaN     NaN   
668           NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
669           NaN     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
670      0.193548     NaN     NaN     NaN     NaN       NaN     NaN     NaN   
671      1.082609     NaN     NaN     NaN     NaN       NaN     NaN     NaN   

movieId  9         10      ...  161084  161155  161594  161830  161918  \
userId                     ...                                           
1           NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
2           NaN  0.513158  ...     NaN     NaN     NaN     NaN     NaN   
3           NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
4           NaN -0.348039  ...     NaN     NaN     NaN     NaN     NaN   
5           NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
...         ...       ...  ...     ...     ...     ...     ...     ...   
667         NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
668         NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
669         NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
670         NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   
671         NaN       NaN  ...     NaN     NaN     NaN     NaN     NaN   

movieId  161944  162376  162542  162672  163949  
userId                                           
1           NaN     NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN     NaN  

[671 rows x 9066 columns]

## ` filling null values with 0 `

In [338]:

centerd_pivoted.fillna(0,inplace=True)
centerd_pivoted

movieId    1       2       3       4       5         6       7       8       \
userId                                                                        
1        0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
2        0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
3        0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
4        0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
5        0.000000     0.0    0.09     0.0     0.0  0.000000     0.0     0.0   
...           ...     ...     ...     ...     ...       ...     ...     ...   
667      0.000000     0.0    0.00     0.0     0.0  0.352941     0.0     0.0   
668      0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
669      0.000000     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
670      0.193548     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   
671      1.082609     0.0    0.00     0.0     0.0  0.000000     0.0     0.0   

movieId  9         10      ...  161084  161155  161594  161830  161918  \
userId                     ...                                           
1           0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
2           0.0  0.513158  ...     0.0     0.0     0.0     0.0     0.0   
3           0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
4           0.0 -0.348039  ...     0.0     0.0     0.0     0.0     0.0   
5           0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
...         ...       ...  ...     ...     ...     ...     ...     ...   
667         0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
668         0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
669         0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
670         0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   
671         0.0  0.000000  ...     0.0     0.0     0.0     0.0     0.0   

movieId  161944  162376  162542  162672  163949  
userId                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...     ...  
667         0.0     0.0     0.0     0.0     0.0  
668         0.0     0.0     0.0     0.0     0.0  
669         0.0     0.0     0.0     0.0     0.0  
670         0.0     0.0     0.0     0.0     0.0  
671         0.0     0.0     0.0     0.0     0.0  

[671 rows x 9066 columns]

In [339]:
from scipy.sparse.linalg import svds
U,sigma,V_T=svds(centerd_pivoted.to_numpy())
sigma=np.diag(sigma)

In [340]:
display(U)
display(sigma)
display(V_T)

array([[ 1.20935444e-04,  5.54846182e-04, -3.13720965e-04,
         3.89264196e-05,  9.66235755e-04, -4.20527749e-04],
       [ 3.55215123e-03,  7.40117565e-03,  4.71337637e-03,
        -1.45026818e-03, -9.30888547e-04, -5.40661313e-03],
       [ 9.64653789e-03,  5.48031438e-03,  5.20402184e-03,
        -7.53891527e-04, -7.52416732e-04, -5.23375717e-03],
       ...,
       [-1.32185775e-03,  2.95561303e-04,  4.81082424e-03,
        -8.73112915e-04, -2.55864182e-03, -9.81731190e-03],
       [ 6.65593753e-03,  2.61521328e-03,  3.11006493e-03,
         4.03140422e-03, -6.35287804e-04, -5.19486704e-03],
       [ 5.51252620e-03,  7.64531565e-03,  2.15610281e-02,
        -4.05056071e-03, -9.70781892e-03, -1.41342939e-02]])

array([[39.29490133,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , 42.15669556,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , 47.56980235,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        , 49.97260177,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , 51.90073918,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        73.54589316]])

array([[-1.65892960e-02, -1.83230220e-02,  2.87034300e-02, ...,
         2.39705533e-04, -1.21141506e-04,  3.28896048e-03],
       [-3.97993031e-02, -8.61939249e-03, -4.46371466e-02, ...,
         2.86267480e-05, -1.44672813e-05, -8.00934225e-03],
       [ 6.10211542e-02, -3.08610082e-03, -1.47077963e-02, ...,
         7.68418551e-05, -3.88340558e-05, -2.42305562e-03],
       [ 6.33823409e-03,  1.52066823e-02, -1.30055326e-02, ...,
         1.30440502e-06, -6.59215441e-07, -1.05694245e-03],
       [-2.31570313e-02,  4.74561174e-03, -2.39072566e-03, ...,
        -3.66687827e-05,  1.85315354e-05,  2.85393917e-02],
       [-4.39847107e-02,  1.67866837e-02,  2.74813102e-02, ...,
        -3.26721438e-05,  1.65117286e-05, -5.95371677e-03]])

In [341]:
display(U.shape)
display(sigma.shape)
display(V_T.shape)

(671, 6)

(6, 6)

(6, 9066)

In [342]:
ans=np.dot(np.dot(U,sigma),V_T)

## ` Reurning data to it's normal values `

In [343]:
ans=ans+avrg.values.reshape(-1,1)
display(ans)
display(pivoted)

array([[2.54829099, 2.54950576, 2.54831668, ..., 2.54999984, 2.55000008,
        2.55147773],
       [3.5039399 , 3.47289695, 3.46375423, ..., 3.48691639, 3.48680456,
        3.48532407],
       [3.58584643, 3.55170683, 3.55555937, ..., 3.56875791, 3.56856152,
        3.56864095],
       ...,
       [3.4002384 , 3.33807538, 3.32698117, ..., 3.35138525, 3.35133422,
        3.35108114],
       [3.82559802, 3.796746  , 3.79382089, ..., 3.80654279, 3.80640554,
        3.80719108],
       [4.01966454, 3.88455975, 3.8694069 , ..., 3.91758344, 3.9172942 ,
        3.90506068]])

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN     4.0     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     NaN     NaN     4.0     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         5.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  161084  161155  161594  161830  161918  161944  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
668         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
670         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
671         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  162376  162542  162672  163949  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
667         NaN     NaN     NaN     NaN  
668         NaN     NaN     NaN     NaN  
669         NaN     NaN     NaN     NaN  
670         NaN     NaN     NaN     NaN  
671         NaN     NaN     NaN     NaN  

[671 rows x 9066 columns]

In [344]:
calc_pred_ratings_df=pd.DataFrame(ans)
calc_pred_ratings_df

0         1         2         3         4         5         6     \
0    2.548291  2.549506  2.548317  2.549922  2.549673  2.549825  2.548529   
1    3.503940  3.472897  3.463754  3.479671  3.470369  3.510934  3.482667   
2    3.585846  3.551707  3.555559  3.564304  3.551826  3.589666  3.561023   
3    4.527627  4.297161  4.209898  4.301913  4.263555  4.437487  4.323739   
4    3.901947  3.924559  3.916233  3.912638  3.905361  3.879471  3.912131   
..        ...       ...       ...       ...       ...       ...       ...   
666  3.671447  3.632301  3.615781  3.637615  3.622381  3.668151  3.641431   
667  3.788428  3.733369  3.717556  3.739820  3.730065  3.777243  3.739459   
668  3.400238  3.338075  3.326981  3.342258  3.337190  3.373012  3.343843   
669  3.825598  3.796746  3.793821  3.803037  3.789770  3.808227  3.796904   
670  4.019665  3.884560  3.869407  3.896240  3.867203  3.979911  3.914571   

         7         8         9     ...      9056      9057      9058  \
0    2.549943  2.549995  2.548918  ...  2.549216  2.549541  2.550038   
1    3.486657  3.485478  3.469381  ...  3.487648  3.489168  3.485952   
2    3.568317  3.567360  3.544734  ...  3.568620  3.573542  3.566720   
3    4.347707  4.340463  4.305579  ...  4.352125  4.352928  4.345573   
4    3.910346  3.910925  3.917906  ...  3.909071  3.920545  3.911057   
..        ...       ...       ...  ...       ...       ...       ...   
666  3.646851  3.645382  3.623996  ...  3.648965  3.651877  3.646058   
667  3.749760  3.748145  3.735711  ...  3.747656  3.751482  3.749030   
668  3.351213  3.349616  3.344498  ...  3.351495  3.349812  3.350270   
669  3.806150  3.805553  3.787263  ...  3.806059  3.811122  3.805061   
670  3.917678  3.913275  3.887899  ...  3.923936  3.936291  3.914058   

         9059      9060      9061      9062      9063      9064      9065  
0    2.551037  2.550764  2.549993  2.549885  2.550000  2.550000  2.551478  
1    3.496192  3.493724  3.486855  3.489521  3.486916  3.486805  3.485324  
2    3.581480  3.578087  3.568662  3.574365  3.568758  3.568562  3.568641  
3    4.336526  4.339565  4.348248  4.355458  4.348161  4.347978  4.340340  
4    3.906042  3.907087  3.909975  3.906821  3.909949  3.910026  3.911751  
..        ...       ...       ...       ...       ...       ...       ...  
666  3.658076  3.655168  3.647081  3.650070  3.647149  3.647013  3.643466  
667  3.751508  3.751110  3.750036  3.752918  3.750053  3.749973  3.754417  
668  3.344024  3.345958  3.351428  3.354605  3.351385  3.351334  3.351081  
669  3.813660  3.811757  3.806488  3.810636  3.806543  3.806406  3.807191  
670  3.917702  3.917620  3.917566  3.927418  3.917583  3.917294  3.905061  

[671 rows x 9066 columns]

In [345]:
meta[meta['id']=='2062']

id                                           overview  \
11567  2062  A rat named Remy dreams of becoming a great Fr...   

                            poster_path        title  vote_average  vote_count  
11567  /jEiEU8viSb8CIIHcfprVr2V6XDz.jpg  Ratatouille           7.5      4510.0

In [346]:
print(f"20 % split is ({np.round(pivoted.shape[0]*0.2)},{np.round(pivoted.shape[1]*0.2)})")

20 % split is (134.0,1813.0)


In [347]:
actual_values = pivoted.iloc[:134, :1813].values
predicted_values = calc_pred_ratings_df.iloc[:134, :1813].values


In [348]:
mask = ~np.isnan(actual_values)
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True, False, ...,  True,  True, False]])

In [349]:
print(predicted_values[mask])

[2.54940621 2.5521786  2.54970281 ... 4.03530821 4.06575023 4.03911536]


In [350]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
print("Mean squared errror",mean_squared_error(actual_values[mask],predicted_values[mask],squared=False))
print("Mean absloute error",mean_absolute_error(actual_values[mask],predicted_values[mask]))

Mean squared errror 0.8636804909951533
Mean absloute error 0.652605840148105


## `Trying to Recommend to user with ID =132`

In [351]:

user_5_ratings = calc_pred_ratings_df.iloc[132,:].sort_values(ascending=False)
print(user_5_ratings)

5017    2.416187
321     2.407947
65      2.407826
2006    2.407521
1843    2.407158
          ...   
1476    2.326106
2385    2.325630
2366    2.325186
951     2.322334
535     2.320362
Name: 132, Length: 9066, dtype: float64


In [352]:
movies_ids=list(user_5_ratings.index[0:100])
movies_ids = list(map(str, movies_ids))

In [353]:
data=meta[meta['id'].isin (movies_ids)]

In [357]:
import requests
from IPython.display import Image, HTML, display
def movie_display(popular_movies):
 getList_name = {}
 for x, xRows in popular_movies.iterrows():

    getResponse = requests.get('https://api.themoviedb.org/3/movie/{}?api_key=c0bda0be71f7815fd6ba2eb5f5c86fd8'.format(xRows['id']) ) # every movie has a unique ID 
    getData = getResponse.json() # we request the data from the API and convert it to json
    
    # a bug fixed because sometimes there are is no poster so it returrns error
    if getData['poster_path']==None:
     continue
    else:   
     getPath = "http://image.tmdb.org/t/p/w500" + getData['poster_path']    # get the path of the poster
     getList_name[xRows['title']] = getPath
 
 
 display(HTML(f"""  < <div style="font-size:24px; font-weight:Bold; color:#fff; text-align:center; padding-top:8px; height:12%; width: 100%; border:1px solid #ccc; border-radius:10px; margin-top:10px; background-color:#FA1A1A;">{"Recommended Movies to user with id 132"}</div> """))   
 # in here he loops on the number of movies to be recommended which is in num_recommend variable in recommend() function
 for i in range(0,popular_movies.shape[0],5):
  

  display( HTML(f"""
                    <table>
                    <tr>
                        <td><img src={list(getList_name.values())[i]} style='border-radius:10px; height:400px; width:575px; border:1px solid #999;'></td>
                        <td><img src={list(getList_name.values())[i+1]} style='border-radius:10px; height:400px; width:575px; border:1px solid #999;'></td>
                        <td><img src={list(getList_name.values())[i+2]} style='border-radius:10px; height:400px; width:575px; border:1px solid #999;'></td>
                        <td><img src={list(getList_name.values())[i+3]} style='border-radius:10px; height:400px; width:575px; border:1px solid #999;'></td>
                        <td><img src={list(getList_name.values())[i+4]} style='border-radius:10px; height:400px; width:575px; border:1px solid #999;'></td>
                        
                    </tr>
                  
                        <td><div style="height:60px; padding-top:15px; text-align:center; font-size:14px; font-weight:bold; border:1px solid #ccc; border-radius:10px;">{list(getList_name.keys())[i+0]}</div></td>
                        <td><div style="height:60px; padding-top:15px; text-align:center; font-size:14px; font-weight:bold; border:1px solid #ccc; border-radius:10px;">{list(getList_name.keys())[i+1]}</div></td>
                        <td><div style="height:60px; padding-top:15px; text-align:center; font-size:14px; font-weight:bold; border:1px solid #ccc; border-radius:10px;">{list(getList_name.keys())[i+2]}</div></td>
                        <td><div style="height:60px; padding-top:15px; text-align:center; font-size:14px; font-weight:bold; border:1px solid #ccc; border-radius:10px;">{list(getList_name.keys())[i+3]}</div></td>
                        <td><div style="height:60px; padding-top:15px; text-align:center; font-size:14px; font-weight:bold; border:1px solid #ccc; border-radius:10px;">{list(getList_name.keys())[i+4]}</div></td>
                    </tr>
                    
                </table>"""))

In [358]:
movie_display(data[0:15])